/**
 * Corteza compose API
 * Corteza compose REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComposeNamespaceNamespaceIDModulePostRequestFieldsInner { 
    fieldID?: string;
    name?: string;
    kind?: string;
    label?: string;
    defaultValue?: Array<string>;
    maxLength?: number;
    isRequired?: boolean;
    isPrivate?: boolean;
    isMulti?: boolean;
    isSystem?: boolean;
    options?: object;
}

