/**
 * Corteza system API
 * Corteza system REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class ActionLogService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Action log events
     * 
     * @param from From
     * @param to To
     * @param beforeActionID Entries before specified action ID
     * @param resource Resource
     * @param action Action
     * @param actorID Filter by one or more actors
     * @param limit Limit
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemActionlogGet(from?: string, to?: string, beforeActionID?: string, resource?: string, action?: string, actorID?: Array<string>, limit?: string, ): Observable<AxiosResponse<any>>;
    public systemActionlogGet(from?: string, to?: string, beforeActionID?: string, resource?: string, action?: string, actorID?: Array<string>, limit?: string, ): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (beforeActionID !== undefined && beforeActionID !== null) {
            queryParameters.append('beforeActionID', <any>beforeActionID);
        }
        if (resource !== undefined && resource !== null) {
            queryParameters.append('resource', <any>resource);
        }
        if (action !== undefined && action !== null) {
            queryParameters.append('action', <any>action);
        }
        if (actorID) {
            actorID.forEach((element) => {
                queryParameters.append('actorID', <any>element);
            })
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/system/actionlog/`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
