export * from './actionLog.service';
import { ActionLogService } from './actionLog.service';
export * from './applications.service';
import { ApplicationsService } from './applications.service';
export * from './attachments.service';
import { AttachmentsService } from './attachments.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authenticationClients.service';
import { AuthenticationClientsService } from './authenticationClients.service';
export * from './dataAccessLayerConnections.service';
import { DataAccessLayerConnectionsService } from './dataAccessLayerConnections.service';
export * from './dataAccessLayerDrivers.service';
import { DataAccessLayerDriversService } from './dataAccessLayerDrivers.service';
export * from './dataAccessLayerSensitivityLevels.service';
import { DataAccessLayerSensitivityLevelsService } from './dataAccessLayerSensitivityLevels.service';
export * from './dataPrivacy.service';
import { DataPrivacyService } from './dataPrivacy.service';
export * from './dataPrivacyRequest.service';
import { DataPrivacyRequestService } from './dataPrivacyRequest.service';
export * from './dataPrivacyRequestComment.service';
import { DataPrivacyRequestCommentService } from './dataPrivacyRequestComment.service';
export * from './integrationGatewayFilters.service';
import { IntegrationGatewayFiltersService } from './integrationGatewayFilters.service';
export * from './integrationGatewayProfiler.service';
import { IntegrationGatewayProfilerService } from './integrationGatewayProfiler.service';
export * from './integrationGatewayRoutes.service';
import { IntegrationGatewayRoutesService } from './integrationGatewayRoutes.service';
export * from './locale.service';
import { LocaleService } from './locale.service';
export * from './messagingQueues.service';
import { MessagingQueuesService } from './messagingQueues.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './reminders.service';
import { RemindersService } from './reminders.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './systemAutomationScripts.service';
import { SystemAutomationScriptsService } from './systemAutomationScripts.service';
export * from './template.service';
import { TemplateService } from './template.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [ActionLogService, ApplicationsService, AttachmentsService, AuthenticationService, AuthenticationClientsService, DataAccessLayerConnectionsService, DataAccessLayerDriversService, DataAccessLayerSensitivityLevelsService, DataPrivacyService, DataPrivacyRequestService, DataPrivacyRequestCommentService, IntegrationGatewayFiltersService, IntegrationGatewayProfilerService, IntegrationGatewayRoutesService, LocaleService, MessagingQueuesService, PermissionsService, RemindersService, ReportsService, RolesService, SettingsService, StatisticsService, SystemAutomationScriptsService, TemplateService, UsersService];
