/**
 * Corteza system API
 * Corteza system REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { SystemDalSensitivityLevelsPostRequest } from '../model/systemDalSensitivityLevelsPostRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class DataAccessLayerSensitivityLevelsService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Search sensitivity levels
     * 
     * @param sensitivityLevelID Filter by sensitivity level ID
     * @param deleted Exclude (0, default), include (1) or return only (2) deleted sensitivity levels
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsGet(sensitivityLevelID?: Array<string>, deleted?: string, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsGet(sensitivityLevelID?: Array<string>, deleted?: string, ): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (sensitivityLevelID) {
            sensitivityLevelID.forEach((element) => {
                queryParameters.append('sensitivityLevelID', <any>element);
            })
        }
        if (deleted !== undefined && deleted !== null) {
            queryParameters.append('deleted', <any>deleted);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/system/dal/sensitivity-levels/`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Create sensitivity level
     * 
     * @param systemDalSensitivityLevelsPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsPost(systemDalSensitivityLevelsPostRequest?: SystemDalSensitivityLevelsPostRequest, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsPost(systemDalSensitivityLevelsPostRequest?: SystemDalSensitivityLevelsPostRequest, ): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/system/dal/sensitivity-levels/`,
                    systemDalSensitivityLevelsPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Remove sensitivity level
     * 
     * @param sensitivityLevelID Connection ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsSensitivityLevelIDDelete(sensitivityLevelID: string, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsSensitivityLevelIDDelete(sensitivityLevelID: string, ): Observable<any> {
        if (sensitivityLevelID === null || sensitivityLevelID === undefined) {
            throw new Error('Required parameter sensitivityLevelID was null or undefined when calling systemDalSensitivityLevelsSensitivityLevelIDDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/system/dal/sensitivity-levels/${encodeURIComponent(String(sensitivityLevelID))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Read connection details
     * 
     * @param sensitivityLevelID Connection ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsSensitivityLevelIDGet(sensitivityLevelID: string, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsSensitivityLevelIDGet(sensitivityLevelID: string, ): Observable<any> {
        if (sensitivityLevelID === null || sensitivityLevelID === undefined) {
            throw new Error('Required parameter sensitivityLevelID was null or undefined when calling systemDalSensitivityLevelsSensitivityLevelIDGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/system/dal/sensitivity-levels/${encodeURIComponent(String(sensitivityLevelID))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update sensitivity details
     * 
     * @param sensitivityLevelID Connection ID
     * @param systemDalSensitivityLevelsPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsSensitivityLevelIDPut(sensitivityLevelID: string, systemDalSensitivityLevelsPostRequest?: SystemDalSensitivityLevelsPostRequest, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsSensitivityLevelIDPut(sensitivityLevelID: string, systemDalSensitivityLevelsPostRequest?: SystemDalSensitivityLevelsPostRequest, ): Observable<any> {
        if (sensitivityLevelID === null || sensitivityLevelID === undefined) {
            throw new Error('Required parameter sensitivityLevelID was null or undefined when calling systemDalSensitivityLevelsSensitivityLevelIDPut.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<any>(`${this.basePath}/system/dal/sensitivity-levels/${encodeURIComponent(String(sensitivityLevelID))}`,
                    systemDalSensitivityLevelsPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Undelete sensitivity level
     * 
     * @param sensitivityLevelID Connection ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public systemDalSensitivityLevelsSensitivityLevelIDUndeletePost(sensitivityLevelID: string, ): Observable<AxiosResponse<any>>;
    public systemDalSensitivityLevelsSensitivityLevelIDUndeletePost(sensitivityLevelID: string, ): Observable<any> {
        if (sensitivityLevelID === null || sensitivityLevelID === undefined) {
            throw new Error('Required parameter sensitivityLevelID was null or undefined when calling systemDalSensitivityLevelsSensitivityLevelIDUndeletePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/system/dal/sensitivity-levels/${encodeURIComponent(String(sensitivityLevelID))}/undelete`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
