/**
 * Corteza compose API
 * Corteza compose REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class AttachmentsService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Delete attachment
     * 
     * @param kind Attachment kind
     * @param namespaceID Namespace ID
     * @param attachmentID Attachment ID
     * @param sign Signature
     * @param userID User ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDDelete(kind: string, namespaceID: string, attachmentID: string, sign?: string, userID?: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDDelete(kind: string, namespaceID: string, attachmentID: string, sign?: string, userID?: string, ): Observable<any> {
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDDelete.');
        }

        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDDelete.');
        }

        if (attachmentID === null || attachmentID === undefined) {
            throw new Error('Required parameter attachmentID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDDelete.');
        }

        let queryParameters = new URLSearchParams();
        if (sign !== undefined && sign !== null) {
            queryParameters.append('sign', <any>sign);
        }
        if (userID !== undefined && userID !== null) {
            queryParameters.append('userID', <any>userID);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/attachment/${encodeURIComponent(String(kind))}/${encodeURIComponent(String(attachmentID))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Attachment details
     * 
     * @param kind Attachment kind
     * @param namespaceID Namespace ID
     * @param attachmentID Attachment ID
     * @param sign Signature
     * @param userID User ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDGet(kind: string, namespaceID: string, attachmentID: string, sign?: string, userID?: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDGet(kind: string, namespaceID: string, attachmentID: string, sign?: string, userID?: string, ): Observable<any> {
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDGet.');
        }

        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDGet.');
        }

        if (attachmentID === null || attachmentID === undefined) {
            throw new Error('Required parameter attachmentID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDGet.');
        }

        let queryParameters = new URLSearchParams();
        if (sign !== undefined && sign !== null) {
            queryParameters.append('sign', <any>sign);
        }
        if (userID !== undefined && userID !== null) {
            queryParameters.append('userID', <any>userID);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/attachment/${encodeURIComponent(String(kind))}/${encodeURIComponent(String(attachmentID))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Serves attached file
     * 
     * @param kind Attachment kind
     * @param namespaceID Namespace ID
     * @param attachmentID Attachment ID
     * @param name File name
     * @param sign Signature
     * @param userID User ID
     * @param download Force file download
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet(kind: string, namespaceID: string, attachmentID: string, name: string, sign?: string, userID?: string, download?: boolean, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet(kind: string, namespaceID: string, attachmentID: string, name: string, sign?: string, userID?: string, download?: boolean, ): Observable<any> {
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet.');
        }

        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet.');
        }

        if (attachmentID === null || attachmentID === undefined) {
            throw new Error('Required parameter attachmentID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet.');
        }

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDOriginalNameGet.');
        }

        let queryParameters = new URLSearchParams();
        if (sign !== undefined && sign !== null) {
            queryParameters.append('sign', <any>sign);
        }
        if (userID !== undefined && userID !== null) {
            queryParameters.append('userID', <any>userID);
        }
        if (download !== undefined && download !== null) {
            queryParameters.append('download', <any>download);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/attachment/${encodeURIComponent(String(kind))}/${encodeURIComponent(String(attachmentID))}/original/${encodeURIComponent(String(name))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Serves preview of an attached file
     * 
     * @param kind Attachment kind
     * @param namespaceID Namespace ID
     * @param attachmentID Attachment ID
     * @param ext Preview extension/format
     * @param sign Signature
     * @param userID User ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet(kind: string, namespaceID: string, attachmentID: string, ext: string, sign?: string, userID?: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet(kind: string, namespaceID: string, attachmentID: string, ext: string, sign?: string, userID?: string, ): Observable<any> {
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet.');
        }

        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet.');
        }

        if (attachmentID === null || attachmentID === undefined) {
            throw new Error('Required parameter attachmentID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet.');
        }

        if (ext === null || ext === undefined) {
            throw new Error('Required parameter ext was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindAttachmentIDPreviewExtGet.');
        }

        let queryParameters = new URLSearchParams();
        if (sign !== undefined && sign !== null) {
            queryParameters.append('sign', <any>sign);
        }
        if (userID !== undefined && userID !== null) {
            queryParameters.append('userID', <any>userID);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/attachment/${encodeURIComponent(String(kind))}/${encodeURIComponent(String(attachmentID))}/preview.${encodeURIComponent(String(ext))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List, filter all page attachments
     * 
     * @param kind Attachment kind
     * @param namespaceID Namespace ID
     * @param sign Signature
     * @param userID User ID
     * @param pageID Filter attachments by page ID
     * @param moduleID Filter attachments by module ID
     * @param recordID Filter attachments by record ID
     * @param fieldName Filter attachments by field name
     * @param limit Limit
     * @param pageCursor Page cursor
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDAttachmentKindGet(kind: string, namespaceID: string, sign?: string, userID?: string, pageID?: string, moduleID?: string, recordID?: string, fieldName?: string, limit?: string, pageCursor?: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDAttachmentKindGet(kind: string, namespaceID: string, sign?: string, userID?: string, pageID?: string, moduleID?: string, recordID?: string, fieldName?: string, limit?: string, pageCursor?: string, ): Observable<any> {
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindGet.');
        }

        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDAttachmentKindGet.');
        }

        let queryParameters = new URLSearchParams();
        if (sign !== undefined && sign !== null) {
            queryParameters.append('sign', <any>sign);
        }
        if (userID !== undefined && userID !== null) {
            queryParameters.append('userID', <any>userID);
        }
        if (pageID !== undefined && pageID !== null) {
            queryParameters.append('pageID', <any>pageID);
        }
        if (moduleID !== undefined && moduleID !== null) {
            queryParameters.append('moduleID', <any>moduleID);
        }
        if (recordID !== undefined && recordID !== null) {
            queryParameters.append('recordID', <any>recordID);
        }
        if (fieldName !== undefined && fieldName !== null) {
            queryParameters.append('fieldName', <any>fieldName);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }
        if (pageCursor !== undefined && pageCursor !== null) {
            queryParameters.append('pageCursor', <any>pageCursor);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/attachment/${encodeURIComponent(String(kind))}/`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
