/**
 * Corteza compose API
 * Corteza compose REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ComposeNamespaceNamespaceIDChartChartIDPostRequest } from '../model/composeNamespaceNamespaceIDChartChartIDPostRequest';
import { ComposeNamespaceNamespaceIDChartPostRequest } from '../model/composeNamespaceNamespaceIDChartPostRequest';
import { ComposeNamespaceNamespaceIDTranslationPatchRequest } from '../model/composeNamespaceNamespaceIDTranslationPatchRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class ChartsService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Delete chart
     * 
     * @param namespaceID Namespace ID
     * @param chartID Chart ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartChartIDDelete(namespaceID: string, chartID: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartChartIDDelete(namespaceID: string, chartID: string, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDDelete.');
        }

        if (chartID === null || chartID === undefined) {
            throw new Error('Required parameter chartID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/${encodeURIComponent(String(chartID))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Read charts by ID
     * 
     * @param namespaceID Namespace ID
     * @param chartID Chart ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartChartIDGet(namespaceID: string, chartID: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartChartIDGet(namespaceID: string, chartID: string, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDGet.');
        }

        if (chartID === null || chartID === undefined) {
            throw new Error('Required parameter chartID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/${encodeURIComponent(String(chartID))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Add/update charts
     * 
     * @param namespaceID Namespace ID
     * @param chartID Chart ID
     * @param composeNamespaceNamespaceIDChartChartIDPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartChartIDPost(namespaceID: string, chartID: string, composeNamespaceNamespaceIDChartChartIDPostRequest?: ComposeNamespaceNamespaceIDChartChartIDPostRequest, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartChartIDPost(namespaceID: string, chartID: string, composeNamespaceNamespaceIDChartChartIDPostRequest?: ComposeNamespaceNamespaceIDChartChartIDPostRequest, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDPost.');
        }

        if (chartID === null || chartID === undefined) {
            throw new Error('Required parameter chartID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/${encodeURIComponent(String(chartID))}`,
                    composeNamespaceNamespaceIDChartChartIDPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List chart translation
     * 
     * @param namespaceID Namespace ID
     * @param chartID ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartChartIDTranslationGet(namespaceID: string, chartID: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartChartIDTranslationGet(namespaceID: string, chartID: string, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDTranslationGet.');
        }

        if (chartID === null || chartID === undefined) {
            throw new Error('Required parameter chartID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDTranslationGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/${encodeURIComponent(String(chartID))}/translation`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update chart translation
     * 
     * @param namespaceID Namespace ID
     * @param chartID ID
     * @param composeNamespaceNamespaceIDTranslationPatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartChartIDTranslationPatch(namespaceID: string, chartID: string, composeNamespaceNamespaceIDTranslationPatchRequest?: ComposeNamespaceNamespaceIDTranslationPatchRequest, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartChartIDTranslationPatch(namespaceID: string, chartID: string, composeNamespaceNamespaceIDTranslationPatchRequest?: ComposeNamespaceNamespaceIDTranslationPatchRequest, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDTranslationPatch.');
        }

        if (chartID === null || chartID === undefined) {
            throw new Error('Required parameter chartID was null or undefined when calling composeNamespaceNamespaceIDChartChartIDTranslationPatch.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/${encodeURIComponent(String(chartID))}/translation`,
                    composeNamespaceNamespaceIDTranslationPatchRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List/read charts
     * 
     * @param namespaceID Namespace ID
     * @param query Search query to match against charts
     * @param handle Search charts by handle
     * @param labels Labels
     * @param limit Limit
     * @param incTotal Include total counter
     * @param pageCursor Page cursor
     * @param sort Sort items
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartGet(namespaceID: string, query?: string, handle?: string, labels?: string, limit?: string, incTotal?: boolean, pageCursor?: string, sort?: string, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartGet(namespaceID: string, query?: string, handle?: string, labels?: string, limit?: string, incTotal?: boolean, pageCursor?: string, sort?: string, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartGet.');
        }

        let queryParameters = new URLSearchParams();
        if (query !== undefined && query !== null) {
            queryParameters.append('query', <any>query);
        }
        if (handle !== undefined && handle !== null) {
            queryParameters.append('handle', <any>handle);
        }
        if (labels !== undefined && labels !== null) {
            queryParameters.append('labels', <any>labels);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }
        if (incTotal !== undefined && incTotal !== null) {
            queryParameters.append('incTotal', <any>incTotal);
        }
        if (pageCursor !== undefined && pageCursor !== null) {
            queryParameters.append('pageCursor', <any>pageCursor);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List/read charts 
     * 
     * @param namespaceID Namespace ID
     * @param composeNamespaceNamespaceIDChartPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public composeNamespaceNamespaceIDChartPost(namespaceID: string, composeNamespaceNamespaceIDChartPostRequest?: ComposeNamespaceNamespaceIDChartPostRequest, ): Observable<AxiosResponse<any>>;
    public composeNamespaceNamespaceIDChartPost(namespaceID: string, composeNamespaceNamespaceIDChartPostRequest?: ComposeNamespaceNamespaceIDChartPostRequest, ): Observable<any> {
        if (namespaceID === null || namespaceID === undefined) {
            throw new Error('Required parameter namespaceID was null or undefined when calling composeNamespaceNamespaceIDChartPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/compose/namespace/${encodeURIComponent(String(namespaceID))}/chart/`,
                    composeNamespaceNamespaceIDChartPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
