/**
 * Corteza system API
 * Corteza system REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemRolesPostRequest1 { 
    /**
     * Name of role
     */
    name?: string;
    /**
     * Handle for role
     */
    handle?: string;
    /**
     * role member IDs
     */
    members?: Array<string>;
    /**
     * Meta
     */
    meta?: string;
    /**
     * Labels
     */
    labels?: string;
}

