/**
 * Corteza system API
 * Corteza system REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemAuthClientsPostRequest { 
    /**
     * Client handle
     */
    handle?: string;
    /**
     * Additional info
     */
    meta?: string;
    /**
     * Valid grants (authorization_code
     */
    validGrant?: string;
    /**
     * Space delimited list of redirect URIs
     */
    redirectURI?: string;
    /**
     * Space delimited list of scopes
     */
    scope?: string;
    /**
     * Is client trusted (skip authorization)
     */
    trusted?: boolean;
    /**
     * Is client enabled
     */
    enabled?: boolean;
    /**
     * Date and time from when client becomes valid
     */
    validFrom?: string;
    /**
     * Date and time from client is no logner valid
     */
    expiresAt?: string;
    /**
     * Security settings
     */
    security?: string;
    /**
     * Labels
     */
    labels?: string;
}

