/**
 * Corteza system API
 * Corteza system REST API definition
 *
 * The version of the OpenAPI document: 2022.9
 * Contact: info@cortezaproject.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemApplicationPostRequest { 
    /**
     * Application name
     */
    name: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Weight for sorting
     */
    weight?: number;
    /**
     * Unify properties
     */
    unify?: string;
    /**
     * Arbitrary JSON holding application configuration
     */
    config?: string;
    /**
     * Labels
     */
    labels?: string;
}

